// ESM wrapper — see ./hero-grid.js for why the source stays a root classic script.
//
// This one matters most: search-vectors.js is GENERATED by build-vectors.html, which
// string-builds the file's text in `window.SearchVectors = {...}` IIFE form. Leaving
// the generated file untouched keeps it byte-compatible with its generator, so
// regenerating the vectors needs no changes to the build tool.
//
// loadPrecomputedVectors() reads window.SearchVectors directly, so the side-effect
// import is what actually matters here; the named export is for consistency.
import '../../search-vectors.js';

export const SearchVectors = window.SearchVectors;
